const express = require("express");

const mongoose = require("mongoose");
const logger = require("logger");

const Food = mongoose.model("Food");
var fs = require("fs");
var multer = require("multer");
const { fileURLToPath } = require("url");
var upload = multer({ dest: "uploads/" }); //setting the default folder for multer
//other imports and code will go here
const router = express.Router();
router.post("/upload", upload.single("fileData"), (req, res, next) => {
  //below code will read the data from the upload folder. Multer     will automatically upload the file in that folder with an  autogenerated name
  fs.readFile(req.file.path, (err, contents) => {
    if (err) {
      console.log("Error: ", err);
    } else {
      res.send({
        message: "Sucessfully added image",
        data: req.file.path,
      });
    }
  });
});
module.exports = router;
